Buildit/Buildit/Areas/Admin/Controllers/AddPublicationController.cs
using Buildit.Common.Providers;
using Buildit.Common.Providers.Contracts;
using Buildit.Services;
using Buildit.Services.Contracts;
using Buildit.Web.Models;
using Buildit.Web.Models.Admin;
using Bytes2you.Validation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Buildit.Areas.Admin.Controllers
{
    [Authorize(Roles = Constants.AdminRole)]
    public class AddPublicationController : Controller
    {
        private readonly IUserProvider userProvider;
        private readonly IServerProvider serverProvider;
        private readonly ICacheProvider cacheProvider;
        private readonly IPublicationService publicationService;
        private readonly IPublicationTypeService publicationTypeService;
        private readonly IMapperAdapter mapper;

        public AddPublicationController(
            IUserProvider userProvider,
            IServerProvider serverProvider,
            ICacheProvider cacheProvider,
            IPublicationService publicationService,
            IPublicationTypeService publicationTypeService,
            IMapperAdapter mapper)
        {
            Guard.WhenArgument(userProvider, "UserProvider").IsNull().Throw();
            Guard.WhenArgument(serverProvider, "ServerProvider").IsNull().Throw();
            Guard.WhenArgument(cacheProvider, "CacheProvider").IsNull().Throw();
            Guard.WhenArgument(publicationService, "PublicationService").IsNull().Throw();
            Guard.WhenArgument(publicationTypeService, "PublicationTypeService").IsNull().Throw();
            Guard.WhenArgument(mapper, "Mapper").IsNull().Throw();

            this.userProvider = userProvider;
            this.serverProvider = serverProvider;
            this.cacheProvider = cacheProvider;
            this.publicationService = publicationService;
            this.publicationTypeService = publicationTypeService;
            this.mapper = mapper;
        }

        public ActionResult Index()
        {
            var model = new AddPublicationViewModel();
            model.PublicationTypes = this.GetPublicationTypes();
            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Index([Bind(Exclude = "PublicationTypes")]AddPublicationViewModel publModel)
        {
            if (!ModelState.IsValid)
            {
                publModel.PublicationTypes = this.GetPublicationTypes();
                return this.View(publModel);
            }

            if (!this.IsImageFile(publModel.Picture))
            {
                this.ModelState.AddModelError("PictureError", Constants.PictureErrorMessage);
                publModel.PublicationTypes = this.GetPublicationTypes();
                return this.View(publModel);
            }

            if (this.publicationService.PublicationFound(publModel.Title))
            {
                this.ModelState.AddModelError("Title", Constants.TitleExistsErrorMessage);
                publModel.PublicationTypes = this.GetPublicationTypes();
                return this.View(publModel);
            }

            var filename = publModel.Picture.FileName;
            var path = this.serverProvider.MapPath(Constants.ImagesRelativePath + filename);
            publModel.Picture.SaveAs(path);

            var publicationModel = this.mapper.Map<PublicationViewModelAdmin>(publModel);
            var publicationId = this.publicationService.AddPublication(publicationModel, filename);

            this.TempData.Add(Constants.AddPublicationSuccessKey, Constants.AddPublicationSuccessMessage);
            return this.Redirect($"/publication/details/{publicationId}");
        }

        private bool IsImageFile(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return false;
            }

            var contentType = file.ContentType.ToLower();
            var result = contentType == "image/jpg"
                || contentType == "image/jpeg"
                || contentType == "image/png";

            return result;
        }

        private IEnumerable<SelectListItem> GetPublicationTypes()
        {
            IEnumerable<SelectListItem> publTypes;
            var cachedTypes = this.cacheProvider.GetValue(Constants.PublicationTypeCache);
            if (cachedTypes != null)
            {
                publTypes = (IEnumerable<SelectListItem>)cachedTypes;
            }
            else
            {
                publTypes = this.publicationTypeService.GetPublicationTypes()
                    .Select(x => new SelectListItem() { Value = x.Id.ToString(), Text = x.Name })
                    .ToList();
                this.cacheProvider.InsertWithSlidingExpiration(Constants.PublicationTypeCache, 
                    publTypes, 
                    Constants.PublicationTypeExpirationInMinutes);
            }

            return publTypes;
        }
    }
}

Buildit/Buildit/Areas/Admin/Views/AddPublication/Index.cshtml
@using Buildit.Web.Models.Admin
@model AddPublicationViewModel
@{
    ViewBag.Title = "Add Publication";
}
<div class="container main-content">
    <h2>Add a publication</h2>

    @using (Html.BeginForm("Index", "AddPublication", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Author, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Author, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Author, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.PublicationTypeId, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.PublicationTypeId, Model.PublicationTypes, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Content, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Content, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Content, "", new { @class = "text-danger" })
            </div>

        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.PublishedOn, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.PublishedOn)
                @Html.ValidationMessageFor(m => m.PublishedOn, "", new { @class = "text-danger" })
            </div>

            <div class='input-group date' id='datetimepicker1'>
                <input type='text' class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Picture, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Picture, new { type = "file" })
                @Html.ValidationMessageFor(m => m.Picture, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Add publication" />
            </div>
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/date")
}